name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: kubernetes-445209
  REGION: us-west1
  GAR_LOCATION: us-west1-docker.pkg.dev/kubernetes-445209/backend-api-python/

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY  }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # Install Docker Compose (if not already available)
      - name: "Install Docker Compose"
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          
      # Build images with Docker Compose
      - name: "Build images using Docker Compose"
        run: docker-compose -f docker-compose.yaml build

      # Push images to Google Artifact Registry
      - name: "Push images using Docker Compose"
        run: docker-compose -f docker-compose.yaml push
